Add pyvista for CI tests
This explicitly installs pyvista in CI runners to prevent test
failures caused by:
ModuleNotFoundError: No module named 'pyvista'