Bump pytest from 8.4.1 to 9.0.3 (#47)
* Bump pytest from 8.4.1 to 9.0.3

Bumps [pytest](https://github.com/pytest-dev/pytest) from 8.4.1 to 9.0.3.
- [Release notes](https://github.com/pytest-dev/pytest/releases)
- [Changelog](https://github.com/pytest-dev/pytest/blob/main/CHANGELOG.rst)
- [Commits](https://github.com/pytest-dev/pytest/compare/8.4.1...9.0.3)

---
updated-dependencies:
- dependency-name: pytest
  dependency-version: 9.0.3
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

* Add pyvista for CI tests

This explicitly installs pyvista in CI runners to prevent test
failures caused by:
ModuleNotFoundError: No module named 'pyvista'

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Pável A. Campos-Peña <pcamposp@uni.pe>